version: '3.3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'dev_user_auth'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
